### PR TITLE
Add BORE BLASTERS

### PR DESCRIPTION
**Pull request by neonlifes**

### CODE REVIEW

**Review by AGulev — APPROVED** [review]

**Comment by neonlifes** [comment]
Hi @AGulev 
There seems to be an error when updating the site. Perhaps this is related to https://github.com/defold/asset-portal/pull/187#issuecomment-2025829720

**Comment by AGulev** [comment]
Should be fine now 
CleanShot 2024-03-29 at 15 17 37@2x

**Comment by neonlifes** [comment]
> Should be fine now 

Thanks @AGulev 
Could you also take a look at the asset portal?

**Comment by AGulev** [comment]
> > Should be fine now
> 
> Thanks @AGulev Could you also take a look at the asset portal?

done

**Comment by neonlifes** [comment]
> > > Should be fine now
> > 
> > 
> > Thanks @AGulev Could you also take a look at the asset portal?
> 
> done

Thanks @AGulev, the game appeared on the showcase page :)
But I meant this: https://github.com/defold/asset-portal/pull/187#issuecomment-2025829720
The latest PRs were not applied to the Asset Portal.

**Pull request merged**
